# -*- coding: utf-8 -*-
"""Mc Donalds app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fudpOd_GetQLkNDQm0cYBoFUDNKAY0ZH
"""

import streamlit as st
import joblib
import pandas as pd

# -------------------------------
# Title and Page Setup
# -------------------------------
st.set_page_config(page_title="Mc Donalds", page_icon="🍔", layout="centered")
st.title("🍟 Mc Donalds Price Predictor")
st.write("Predict the **Big Mac Price** based on the New Hourly Wage Rate.")

# -------------------------------
# Load Model Safely
# -------------------------------
@st.cache_resource
def load_model():
    try:
        model = joblib.load("Mc Donalds.pkl")
        return model
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

model = load_model()

# -------------------------------
# User Input
# -------------------------------
hourly_wage = st.number_input(
    "Enter New Hourly Wage Rate ($)",
    min_value=0.0,
    step=0.1,
    format="%.2f"
)

# -------------------------------
# Prediction Logic
# -------------------------------
if st.button("Predict Big Mac Price"):
    if model is not None:
        try:
            # Create DataFrame with constant column for OLS model
            X_input = pd.DataFrame({'const': [1], 'New Hourly Wage': [hourly_wage]})
            prediction = model.predict(X_input)[0]
            st.success(f"🍔 Predicted Big Mac Price: **${prediction:.2f}**")
        except Exception as e:
            st.error(f"Prediction failed: {e}")
    else:
        st.error("Model could not be loaded. Please ensure 'Mc Donalds.pkl' is in the same folder.")

# -------------------------------
# Footer
# -------------------------------
st.markdown("---")
st.caption("Developed for Mc Donalds Pricing Model using Streamlit & Joblib.")